### PR TITLE
prefer ts private keyword instead of # prefix

### PR DESCRIPTION
**Pull request by carlegbert**
Hey there,
I've been running into some issues with an application that depends on this library. I'm fairly sure that this is not a bug with antlr4g per se; I kind of suspect it has to do with some arcane corner case in the build process that produces the bundle. Here goes:

After setting a bunch of breakpoints trying to track down an issue in some code that has antlr4ng as a transitive dependency, I ended up in the `addSet` method of `IntervalSet`: https://github.com/mike-lischke/antlr4ng/blob/main/src/misc/IntervalSet.ts#L164
Breakpoints set after that line don't catch, & after configuring the debugger to catch on caught + uncaught exceptions: 
image
And, strangely, although `this` and `other` are both an `_IntervalSet`, their prototypes are not referentially equal:
image
I have no idea exactly why this would be the case, since they are ostensibly instances of the same class, but it seems likely it has something to do with the compiled + bundled typescript creating two identical copies of the `IntervalSet` class for whatever reason, or something like that. Presumably, this is not caught in tests because vitest does not use a bundle identical to the one that is published to npm (or maybe it's some difference in the runtime).

Whatever the exact cause, I'm fairly sure that this issue would go away with a few small changes to use the typescript `private` keyword instead of the built-in `#` private prefix, so for your consideration is a patch that does just that. I made this change in every place where this likely would be able to happen. If you think it would be better to add some public getters instead, I'd be happy to update the PR to do that (although since some of the properties involved are arrays, that's a little bit of a slippery slope & would require some changes that are not as trivial as this one).

Thanks for reading this strange tale; it's definitely one of the more perplexing issues I have run across.

### CODE REVIEW

**Comment by mike-lischke** [comment]
The reported problem is not about private fields, but VS Code (or rather V8) not being able to deal with that all the time correctly. Access modifiers are just syntactic sugar, as you certainly know. Coming from other, strongly typed languages like the idea of keeping real private, what's supposed to be private.

But I'm not totally opposed to use `private` instead of `#`, because there are other small issues with it, one being that depending on the target version, bundlers might wrap private fields in weak maps, creating so additional code that may slow down code execution. Also the syntax itself is a nuisance.

**Comment by carlegbert** [comment]
> The reported problem is not about private fields, but VS Code (or rather V8) not being able to deal with that all the time correctly. Access modifiers are just syntactic sugar, as you certainly know.

FWIW, the same thing also happens in Firefox as well Safari (I'm running into this issue in an application that runs in the browser using Monaco), so it is not only limited to v8.

> Coming from other, strongly typed languages I like the idea of keeping really private, what's supposed to be private.

That's fair- I also experimented with a branch that mostly added getters, & kept the `#`, but because of array-mutating calls like this one: https://github.com/mike-lischke/antlr4ng/blob/main/src/misc/IntervalSet.ts#L321 the diff ends up a bit bigger, tests are needed, etc. Of course I am happy to change this PR to take that approach if you think that's better.

**Comment by mike-lischke** [comment]
But replacing private fields in only a few places makes not much sense. If we replace it, it should happen in all places.

**Comment by carlegbert** [comment]
> But replacing private fields in only a few places makes not much sense. If we replace it, it should happen in all places.

Sure, that makes sense- I guess it would be easy for the problem to creep up again accidentally otherwise. I can update the PR to do that in a bit.

**Comment by carlegbert** [comment]
@mike-lischke I've now renamed _almost_ all of the `#` fields to just be normal private fields. The small handful that are remaining are the ones where the field is accessible via getters/setters. Changing the interface of those getters/setters is sometimes not completely trivial because they often are implementing or overriding some method from an abstract class. Maybe in those cases I should just rename `#somePrivateFieldWithAGetter` to `_somePrivateFieldWithAGetter` or something similar?

**Comment by mike-lischke** [comment]
Very interesting read: https://lea.verou.me/blog/2023/04/private-fields-considered-harmful/

**Comment by carlegbert** [comment]
> Very interesting read: https://lea.verou.me/blog/2023/04/private-fields-considered-harmful/
> 
> Given that it's clear that's not a good idea to use private fields, if you want your library to be used without problems in all (relevant) setups.

Interesting! I'm not sure whether or not use of proxies were involved with the issue I was running into. It's definitely possible.

**Comment by carlegbert** [comment]
Thanks @mike-lischke!

**Pull request merged**
